### ISSUE TITLE
URL in description and README broken

### ISSUE THREAD

**Issue by paromitaroy** [prgithubschool/github-games-dbbloke#2]
The URL in the repository description and README are pointing to prgithubschool's copy of the game instead of yours.

Please fix both, so they point to your copy of the game at https://prgithubschool.github.io/github-games-dbbloke.

**Comment by dbbloke** [comment]
Thanks, yes i noticed almost immediately and updated the URL. 2nd commit here. 
https://github.com/prgithubschool/github-games-dbbloke/commit/41e79dc5af06c23453dc69e60ef91676044d8556
